In [1]:
import scipy.signal as signal
import pylab
import numpy
pylab.rcParams['savefig.dpi'] = 100 # default 72
%config InlineBackend.figure_formats=['svg'] # SVG inline viewing

Exemplo 4.4

In [2]:
numpy.convolve([2,3,4],[3,4,5,6])

array([ 6, 17, 34, 43, 38, 24])

a convolução desses dois vetores resulta nos coeficientes dos polinômios de $X_3$, pois pela 8 propriedade $X_3(z)=X_2(z) X_1(z)$

In [3]:
x1 = [1,2,3]
x2 = [2,4,3,5]
numpy.convolve(x1,x2)

array([ 2,  8, 17, 23, 19, 15])

## Transformada inversa Z

Para conseguir a transformada inversa de uma função $X(z)$, podemos calcular usando frações parciais com os coeficientes de $z$:

Por exemplo, com a função:
$X(z)=\frac{z^{-1}}{3-4z^{-1}+z^{-2}}$

In [4]:
## Numerador (invertidos para ajeitar o resultado)
b = [0, 1]
## Denominador
a = [3,-4,1]

In [5]:
[r,p,k] = signal.residue(b, a)

In [6]:
# Numerador
r

array([-0.5,  0.5])

In [7]:
# Denominador
p

array([0.33333333, 1.        ])

Invertendo os resultados, podemos montar o resultado obtido assim:
$X(z)=-\frac{\frac 1 2}{1-z^{-1}} + \frac{\frac 1 2}{1-\frac 1 3 z^{-1}}$

Para conseguir a transformada inversa de uma função $X(z)$, podemos calcular usando frações parciais com os coeficientes de $z$:

Por exemplo, com a função:
$X(z)=\frac{z^{-1}}{3-4z^{-1}+z^{-2}}$

In [8]:
## Numerador
b = [0, 1]
## Denominador
a = [3,-4,1]

In [9]:
[r,p,k] = signal.residue(b, a)

In [10]:
# Numerador
r

array([-0.5,  0.5])

In [11]:
# Denominador
p

array([0.33333333, 1.        ])

Invertendo os resultados, podemos montar o resultado obtido assim:
$X(z)=-\frac{\frac 1 2}{1-z^{-1}} + \frac{\frac 1 2}{1-\frac 1 3 z^{-1}}$

Para conseguir a transformada inversa de uma função $X(z)$, podemos calcular usando frações parciais com os coeficientes de $z$:

Por exemplo, com a função:
$X(z)=\frac{z^{-1}}{3-4z^{-1}+z^{-2}}$

In [12]:
## Numerador
b = [0, 1]
## Denominador
a = [3,-4,1]

In [13]:
[r,p,k] = signal.residue(b, a)

In [14]:
# Numerador
## Dando resultado inverrtido do livro???
r

array([-0.5,  0.5])

In [15]:
# Denominador
p

array([0.33333333, 1.        ])

In [16]:
k

array([], dtype=float64)

Podemos montar o resultado obtido assim:
$X(z)=-\frac{\frac 1 2}{1-z^{-1}} + \frac{\frac 1 2}{1-\frac 1 3 z^{-1}}$

    ## Soluções de equações de diferença

Por exemplo, com a função:
$X(z)=\frac{z^{-1}}{3-4z^{-1}+z^{-2}}$

In [17]:
## Numerador
b = [0, 1]
## Denominador
a = [3,-4,1]

In [18]:
[r,p,k] = signal.residue(b, a)

In [19]:
# Numerador
## Dando resultado inverrtido do livro???
r

array([-0.5,  0.5])

In [20]:
# Denominador
p

array([0.33333333, 1.        ])

In [21]:
k

array([], dtype=float64)

Podemos montar o resultado obtido assim:
$X(z)=-\frac{\frac 1 2}{1-z^{-1}} + \frac{\frac 1 2}{1-\frac 1 3 z^{-1}}$

## Soluções de equações de diferença