In [26]:
import sk_dsp_comm.sigsys as ss
import scipy.signal as signal
from IPython.display import Image, SVG
import pylab
import numpy
pylab.rcParams['savefig.dpi'] = 100 # default 72
%config InlineBackend.figure_formats=['svg'] # SVG inline viewing

Exemplo 4.4

In [27]:
numpy.convolve([2,3,4],[3,4,5,6])

array([ 6, 17, 34, 43, 38, 24])

a convolução desses dois vetores resulta nos coeficientes dos polinômios de $X_3$, pois pela 8 propriedade $X_3(z)=X_2(z) X_1(z)$

In [28]:
x1 = [1,2,3]
x2 = [2,4,3,5]
numpy.convolve(x1,x2)

array([ 2,  8, 17, 23, 19, 15])

## Transformada inversa Z

Para conseguir a transformada inversa de uma função $X(z)$, podemos calcular usando frações parciais com os coeficientes de $z$:

Por exemplo, com a função:
$X(z)=\frac{z^{-1}}{3-4z^{-1}+z^{-2}}$

In [29]:
## Numerador
b = [0, 1]
## Denominador
a = [3,-4,1]

In [30]:
[r,p,k] = signal.residue(b, a)

In [31]:
# Numerador
## Dando resultado inverrtido do livro???
r

array([-0.5,  0.5])

In [32]:
# Denominador
p

array([0.33333333, 1.        ])

In [33]:
k

array([], dtype=float64)

Podemos montar o resultado obtido assim:
$X(z)=-\frac{\frac 1 2}{1-z^{-1}} + \frac{\frac 1 2}{1-\frac 1 3 z^{-1}}$